'use client';

import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import type { PropFirmPayout, PropFirmTrade } from '@/types';

const date = new Date().toISOString().slice(0, 10);
const EMPTY_TRADE = { date, phase: 'evaluation', symbol: 'MNQ', side: 'LONG', entry_time: '', exit_time: '', qty: '1', pnl_points: '', pnl_usd: '', fee: '0', strategy: '', exit_reason: '', notes: '' };
const EMPTY_PAYOUT = { date, amount_usd: '', notes: '' };
type TradeForm = typeof EMPTY_TRADE;
function tradeForm(record: PropFirmTrade): TradeForm { return { date: record.date, phase: record.phase, symbol: record.symbol, side: record.side, entry_time: record.entry_time, exit_time: record.exit_time, qty: String(record.qty), pnl_points: String(record.pnl_points), pnl_usd: String(record.pnl_usd), fee: String(record.fee), strategy: record.strategy ?? '', exit_reason: record.exit_reason ?? '', notes: record.notes ?? '' }; }

export default function PropFirmPage() {
  const [trades, setTrades] = useState<PropFirmTrade[]>([]); const [payouts, setPayouts] = useState<PropFirmPayout[]>([]);
  const [trade, setTradeState] = useState<TradeForm>(EMPTY_TRADE); const [payout, setPayout] = useState(EMPTY_PAYOUT);
  const [editingTrade, setEditingTrade] = useState<string | null>(null); const [editingPayout, setEditingPayout] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const load = async () => { const [a, b] = await Promise.all([fetch('/api/prop-firm/trades?start=2000-01-01&end=2100-01-01'), fetch('/api/prop-firm/payouts?start=2000-01-01&end=2100-01-01')]); if (a.ok) setTrades(await a.json()); if (b.ok) setPayouts(await b.json()); if (!a.ok || !b.ok) toast.error('Could not load prop-firm records'); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const setTrade = (key: keyof TradeForm, value: string) => setTradeState((current) => ({ ...current, [key]: value }));
  const summary = useMemo(() => ({ trading: trades.reduce((sum, item) => sum + item.pnl_usd - item.fee, 0), payouts: payouts.reduce((sum, item) => sum + item.amount_usd, 0), evaluations: trades.filter((item) => item.phase === 'evaluation').length, funded: trades.filter((item) => item.phase === 'funded').length }), [trades, payouts]);
  const submitTrade = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const body = { ...trade, qty: Number(trade.qty), pnl_points: Number(trade.pnl_points), pnl_usd: Number(trade.pnl_usd), fee: Number(trade.fee), strategy: trade.strategy || null, exit_reason: trade.exit_reason || null, notes: trade.notes || null }; const response = await fetch(editingTrade ? `/api/prop-firm/trades/${editingTrade}` : '/api/prop-firm/trades', { method: editingTrade ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); setSaving(false); if (!response.ok) return toast.error((await response.json().catch(() => null))?.error ?? 'Could not save trade'); toast.success(editingTrade ? 'Trade updated' : 'Trade recorded'); setTradeState(EMPTY_TRADE); setEditingTrade(null); void load(); };
  const submitPayout = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(editingPayout ? `/api/prop-firm/payouts/${editingPayout}` : '/api/prop-firm/payouts', { method: editingPayout ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...payout, amount_usd: Number(payout.amount_usd), notes: payout.notes || null }) }); if (!response.ok) return toast.error('Could not save payout'); toast.success(editingPayout ? 'Payout updated' : 'Payout recorded'); setPayout(EMPTY_PAYOUT); setEditingPayout(null); void load(); };
  const remove = async (path: string) => { if (!confirm('Delete this record?')) return; const response = await fetch(path, { method: 'DELETE' }); if (!response.ok) return toast.error('Could not delete record'); toast.success('Record deleted'); void load(); };
  return <div className="space-y-6"><section><p className="text-xs font-mono uppercase tracking-widest text-[#8A8F98]">Separate ledger</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#EDEDEF]">Prop Firm Journal</h1><p className="mt-2 max-w-2xl text-sm text-[#8A8F98]">Keep evaluation and funded-account performance separate from the standard trade journal. This page is recordkeeping only; it has no broker connection or order controls.</p></section>
    <section className="grid gap-3 sm:grid-cols-4">{[['Trading net',summary.trading],['Payouts',summary.payouts],['Evaluation trades',summary.evaluations],['Funded trades',summary.funded]].map(([label,value]) => <div key={String(label)} className="rounded-2xl border border-white/[0.06] bg-gradient-to-b from-white/[0.06] to-white/[0.02] p-4"><p className="text-xs text-[#8A8F98]">{label}</p><p className={typeof value === 'number' && value < 0 ? 'mt-2 text-2xl font-semibold text-rose-400' : 'mt-2 text-2xl font-semibold text-[#EDEDEF]'}>{typeof value === 'number' && String(label).includes('trades') ? value : `$${Number(value).toFixed(2)}`}</p></div>)}</section>
    <form onSubmit={submitTrade} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="text-lg font-medium text-[#EDEDEF]">{editingTrade ? 'Edit trade' : 'Record trade'}</h2><div className="mt-4 grid gap-3 md:grid-cols-4">{([['date','Date','date'],['phase','Phase','phase'],['symbol','Symbol','text'],['side','Side','side'],['qty','Quantity','number'],['entry_time','Entry time','datetime-local'],['exit_time','Exit time','datetime-local'],['pnl_points','P&L points','number'],['pnl_usd','Gross P&L (USD)','number'],['fee','Fees (USD)','number'],['strategy','Strategy','text'],['exit_reason','Exit reason','reason']] as const).map(([key,label,type]) => <label key={key} className="text-xs text-[#8A8F98]">{label}{type === 'phase' ? <select value={trade.phase} onChange={(e) => setTrade('phase', e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]"><option value="evaluation">Evaluation</option><option value="funded">Funded</option></select> : type === 'side' ? <select value={trade.side} onChange={(e) => setTrade('side', e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]"><option>LONG</option><option>SHORT</option></select> : type === 'reason' ? <select value={trade.exit_reason} onChange={(e) => setTrade('exit_reason', e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]"><option value="">Not specified</option>{['TP','SL','BE','manual','time','other'].map((value) => <option key={value}>{value}</option>)}</select> : <input required={key !== 'strategy'} type={type} step={type === 'number' ? 'any' : undefined} value={trade[key]} onChange={(e) => setTrade(key, e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF] focus:border-[#5E6AD2] focus:outline-none" />}</label>)}</div><label className="mt-3 block text-xs text-[#8A8F98]">Notes<textarea value={trade.notes} onChange={(e) => setTrade('notes', e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-white/10 bg-[#0F0F12] p-3 text-sm text-[#EDEDEF]" /></label><div className="mt-4 flex gap-3"><button disabled={saving} className="rounded-lg bg-[#5E6AD2] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? 'Saving…' : editingTrade ? 'Update trade' : 'Record trade'}</button>{editingTrade && <button type="button" onClick={() => { setEditingTrade(null); setTradeState(EMPTY_TRADE); }} className="text-sm text-[#8A8F98]">Cancel</button>}</div></form>
    <section className="overflow-hidden rounded-2xl border border-white/[0.06] bg-white/[0.02]"><div className="border-b border-white/[0.06] px-5 py-4 text-sm font-medium text-[#EDEDEF]">Trades</div>{trades.length === 0 ? <p className="p-5 text-sm text-[#8A8F98]">No prop-firm trades yet.</p> : <div className="divide-y divide-white/[0.06]">{trades.slice().reverse().map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><div><b className="text-[#EDEDEF]">{item.date} · {item.phase} · {item.symbol}</b><span className="ml-3 text-[#8A8F98]">{item.side} · {item.qty} contracts</span></div><div className="flex gap-3"><span className={item.pnl_usd-item.fee >= 0 ? 'text-emerald-400' : 'text-rose-400'}>{item.pnl_usd-item.fee >= 0 ? '+' : ''}${(item.pnl_usd-item.fee).toFixed(2)}</span><button onClick={() => { setTradeState(tradeForm(item)); setEditingTrade(item.id); }} className="text-[#8A8F98]">Edit</button><button onClick={() => void remove(`/api/prop-firm/trades/${item.id}`)} className="text-rose-400">Delete</button></div></div>)}</div>}</section>
    <form onSubmit={submitPayout} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="text-lg font-medium text-[#EDEDEF]">{editingPayout ? 'Edit payout' : 'Record payout'}</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-[#8A8F98]">Date<input required type="date" value={payout.date} onChange={(e) => setPayout({ ...payout, date: e.target.value })} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]" /></label><label className="text-xs text-[#8A8F98]">Amount (USD)<input required type="number" min="0.01" step="0.01" value={payout.amount_usd} onChange={(e) => setPayout({ ...payout, amount_usd: e.target.value })} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]" /></label><label className="text-xs text-[#8A8F98]">Notes<input value={payout.notes} onChange={(e) => setPayout({ ...payout, notes: e.target.value })} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]" /></label></div><div className="mt-4 flex gap-3"><button className="rounded-lg bg-white/[0.08] px-4 py-2 text-sm text-[#EDEDEF] hover:bg-white/[0.12]">{editingPayout ? 'Update payout' : 'Record payout'}</button>{editingPayout && <button type="button" onClick={() => { setPayout(EMPTY_PAYOUT); setEditingPayout(null); }} className="text-sm text-[#8A8F98]">Cancel</button>}</div></form>
    <section className="overflow-hidden rounded-2xl border border-white/[0.06] bg-white/[0.02]"><div className="border-b border-white/[0.06] px-5 py-4 text-sm font-medium text-[#EDEDEF]">Payouts</div>{payouts.length === 0 ? <p className="p-5 text-sm text-[#8A8F98]">No payouts yet.</p> : <div className="divide-y divide-white/[0.06]">{payouts.slice().reverse().map((item) => <div key={item.id} className="flex justify-between px-5 py-3 text-sm"><span className="text-[#EDEDEF]">{item.date}{item.notes ? ` · ${item.notes}` : ''}</span><span className="flex gap-3"><span className="text-emerald-400">+${item.amount_usd.toFixed(2)}</span><button onClick={() => { setPayout({ date: item.date, amount_usd: String(item.amount_usd), notes: item.notes ?? '' }); setEditingPayout(item.id); }} className="text-[#8A8F98]">Edit</button><button onClick={() => void remove(`/api/prop-firm/payouts/${item.id}`)} className="text-rose-400">Delete</button></span></div>)}</div>}</section>
  </div>;
}
