'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import type { DailyReview } from '@/types';

const today = new Date().toISOString().slice(0, 10);
const BLANK = { status: 'draft', structure: '', scenario_a: '', scenario_b: '', scenario_c: '', rule_followed: null as boolean | null, error_tags: '', lesson: '', next_action: '' };

export default function DailyReviewPage() {
  const [date, setDate] = useState(today); const [form, setForm] = useState(BLANK); const [saving, setSaving] = useState(false);
  const load = async (value: string) => { const response = await fetch(`/api/daily-reviews/${value}`); if (!response.ok) return toast.error('Could not load review'); const { record } = await response.json() as { record: DailyReview | null }; setForm(record ? { status: record.status, structure: record.structure ?? '', scenario_a: record.scenario_a ?? '', scenario_b: record.scenario_b ?? '', scenario_c: record.scenario_c ?? '', rule_followed: record.rule_followed, error_tags: record.error_tags.join(', '), lesson: record.lesson ?? '', next_action: record.next_action ?? '' } : BLANK); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(date); }, 0); return () => window.clearTimeout(timer); }, [date]);
  const set = (key: keyof typeof form, value: string | boolean | null) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const response = await fetch(`/api/daily-reviews/${date}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, error_tags: form.error_tags.split(',').map((tag) => tag.trim()).filter(Boolean) }) }); setSaving(false); if (!response.ok) return toast.error((await response.json().catch(() => null))?.error ?? 'Could not save review'); toast.success(form.status === 'completed' ? 'Daily review completed' : 'Draft saved'); };
  return <div className="space-y-6"><section><p className="text-xs font-mono uppercase tracking-widest text-[#8A8F98]">Qualitative journal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#EDEDEF]">Daily Review</h1><p className="mt-2 max-w-2xl text-sm text-[#8A8F98]">Capture the plan, scenarios, discipline, and lesson for a session. It does not alter P&L or trading statistics.</p></section>
    <form onSubmit={save} className="rounded-2xl border border-white/[0.06] bg-gradient-to-b from-white/[0.06] to-white/[0.02] p-5 shadow-[0_0_0_1px_rgba(255,255,255,0.04),0_8px_32px_rgba(0,0,0,0.25)]"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-[#8A8F98]">Session date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 block h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]" /></label><label className="text-xs text-[#8A8F98]">Status<select value={form.status} onChange={(event) => set('status', event.target.value)} className="mt-1 block h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]"><option value="draft">Draft</option><option value="completed">Completed</option></select></label></div>
      {([['structure','Market structure / context'],['scenario_a','Primary scenario'],['scenario_b','Alternative scenario'],['scenario_c','Invalidation / third scenario'],['lesson','Lesson'],['next_action','Next action']] as const).map(([key,label]) => <label key={key} className="mt-4 block text-xs text-[#8A8F98]">{label}<textarea value={form[key]} maxLength={1000} onChange={(event) => set(key, event.target.value)} className="mt-1 block min-h-20 w-full rounded-lg border border-white/10 bg-[#0F0F12] p-3 text-sm text-[#EDEDEF] focus:border-[#5E6AD2] focus:outline-none" /></label>)}
      <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs text-[#8A8F98]">Rule adherence<select value={form.rule_followed === null ? '' : String(form.rule_followed)} onChange={(event) => set('rule_followed', event.target.value === '' ? null : event.target.value === 'true')} className="mt-1 block h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]"><option value="">Not assessed</option><option value="true">Followed</option><option value="false">Not followed</option></select></label><label className="text-xs text-[#8A8F98]">Error tags (comma-separated)<input value={form.error_tags} onChange={(event) => set('error_tags', event.target.value)} maxLength={1000} className="mt-1 block h-10 w-full rounded-lg border border-white/10 bg-[#0F0F12] px-3 text-sm text-[#EDEDEF]" /></label></div>
      <button disabled={saving} className="mt-5 rounded-lg bg-[#5E6AD2] px-4 py-2 text-sm font-medium text-white shadow-[0_4px_12px_rgba(94,106,210,0.3)] hover:bg-[#6872D9] disabled:opacity-50">{saving ? 'Saving…' : form.status === 'completed' ? 'Save completed review' : 'Save draft'}</button>
    </form></div>;
}
